### ISSUE TITLE
Why do u choose Solr

### ISSUE THREAD

**Issue by HelloTo4x** [natliblux/BnLMetsExporter#1]
Hi, i am reading your project, why do you choose Solr instead of other search engines such as Elastic search... Can u tell your purpose, the pros and cons of Solr if you know, thank u so much

**Comment by Ra1phM** [comment]
Solr and Elasticsearch share similarities since they both use Lucene. Solr is more focused on text search and offers a nice-to-have admin interface as well and this is why we chose it. At the BnL, we also use Elasticsearch but more for analytics.
